# Generated by Django 2.2.6 on 2019-10-31 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20191031_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesection',
            name='gamedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 31, 8, 52, 48, 985246)),
        ),
    ]
