# Generated by Django 2.2.6 on 2019-11-06 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_auto_20191031_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesection',
            name='gamedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 16, 11, 28, 915350)),
        ),
    ]
