# Generated by Django 2.2.6 on 2019-11-06 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_auto_20191105_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='payno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('useramount', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesection',
            name='gamedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 16, 28, 15, 61390)),
        ),
    ]
