# Generated by Django 2.2.6 on 2019-11-06 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0019_auto_20191105_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesection',
            name='gamedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 17, 51, 35, 909956)),
        ),
    ]
