# Generated by Django 2.2.6 on 2019-10-31 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='umanagedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('gameno', models.CharField(max_length=50)),
                ('gamename', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=15)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 31, 8, 37, 4, 136214))),
                ('usersc', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
