# Generated by Django 2.2.6 on 2019-10-31 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_umanagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umanagedata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 31, 8, 52, 32, 449300)),
        ),
    ]
